[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    knolleary/PubSubClient@^2.8      ; MQTT client
    bblanchon/ArduinoJson@^7         ; JSON serialization
    arduino-libraries/NTPClient@^3.2 ; Epoch time sync
    https://github.com/tzapu/WiFiManager.git@^2.0.16-rc.2

build_flags =
    -DCORE_DEBUG_LEVEL=3             ; Info level logs
